stages:
  - build
  - test
  - deploy
  - production
  
image: node:latest

cache:
  paths:
    - node_modules/

build:
    stage: build
    script:
      - npm install
    artifacts:
      paths:
        - node_modules/
test:
    stage: test
    script:
      - npm install
      - npm test
    artifacts:
        paths:
        - node_modules/
deploy-test:
  stage: deploy
  environment:
    name: staging
    url: 192.168.124.100
  script:
    - ssh dgx1@192.168.124.100 "cd /raid/Dataset/eclass && git checkout develop && git pull origin develop && npm install && node server.js && exit"
  only:
    - develop