stages:
  - build
  - test
  - deploy
  
image: node:latest

variables:
  CI_PROJECT_URL="http://git.ycs.com/ycs/ai/eclassweb/"

  cache:
  paths:
    - node_modules/

build:
    stage: build
    script:
      - npm install
    artifacts:
      paths:
        - node_modules/
test:
    stage: test
    script:
      - npm install
      - node server.js
    artifacts:
        paths:
        - node_modules/