.run-dev-fixtures:
  extends:
    - .default-retry
    - .rails-cache
    - .default-before_script
    - .use-pg11
  stage: test
  needs: ["setup-test-env"]
  variables:
    FIXTURE_PATH: "db/fixtures/development"
    SEED_CYCLE_ANALYTICS: "true"
    SEED_PRODUCTIVITY_ANALYTICS: "true"
    CYCLE_ANALYTICS_ISSUE_COUNT: 1
    SIZE: 0  # number of external projects to fork, requires network connection
    # SEED_NESTED_GROUPS: "false" # requires network connection

run-dev-fixtures:
  extends:
    - .run-dev-fixtures
    - .dev-fixtures:rules:ee-and-foss
  script:
    - run_timed_command "scripts/gitaly-test-build"
    - run_timed_command "scripts/gitaly-test-spawn"
    - run_timed_command "RAILS_ENV=test bundle exec rake db:seed_fu"

run-dev-fixtures-ee:
  extends:
    - .run-dev-fixtures
    - .dev-fixtures:rules:ee-only
    - .use-pg11-ee
  script:
    - run_timed_command "scripts/gitaly-test-build"
    - run_timed_command "scripts/gitaly-test-spawn"
    - cp ee/db/fixtures/development/* $FIXTURE_PATH
    - run_timed_command "RAILS_ENV=test bundle exec rake db:seed_fu"
